### ISSUE TITLE
Importing geemap

### ISSUE THREAD

**Issue by luiqs** [giswqs/geebook#3]
Hi, I just bought your new book and I am very excited to start learning. I hope you can help me whit this issue: 

![image](https://github.com/giswqs/geebook/assets/57743342/476463b4-2ded-434c-8079-de197597e7bb)

![image](https://github.com/giswqs/geebook/assets/57743342/1a5f5389-7762-4b74-8110-27f9be760ed3)

I tried to install pillow separately, it looks that is just fine
![image](https://github.com/giswqs/geebook/assets/57743342/6f8e2bdf-8c0b-4ac7-9371-69a855812ce7)

**Comment by giswqs** [comment]
This seems a PIL issue on Windows. Are you using Python 3.11? Try 3.10

conda remove -n gee --all -y

conda create -n gee python=3.10
conda activate gee
conda install -c conda-forge mamba
mamba install -c conda-forge geemap

**Comment by luiqs** [comment]
> 

Qiusheng Wu thanks a lot! The python version fix the problem!

**Comment by giswqs** [comment]
Fixed in https://github.com/gee-community/geemap/pull/1649
